title: "Test"
url: "https://monsoonmalabar.com/chackojustine77u886bhjhl"
email: "chackojustine77u886bhjhlpooo77@gmail.com"
markdown: kramdown
mobile: "918330828455"
country: "Afghanistan"
currency_code: "AED"
paypal_email: ""
razorpay_key: ""
location: "9.9778657,76.2832192"
category: "Kirana Store, FMCG & Grocery"
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 10
permalink: /:categories/:title/
paginate_path: 'page/:num/'
favicon: "https://monsoonmalabar.com/chackojustine77u886bhjhl/logo.png"
paypal: 
fb_appid: ""
analytics: 
adsense: 